linters:
  # disable-all: true
  enable:
    - gofumpt
    - durationcheck
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gochecknoglobals
    - errorlint
    - exhaustive
    - funlen
issues:
  max-same-issues: 0
