name: Create Release Note

on:
  schedule:
    - cron: "0 5 * * 2"
  workflow_dispatch:

jobs:
  create-release-pr:
    uses: matsuri-tech/matsuri-workflows/.github/workflows/create-release-pr.yml@a293e3fcbaef01ef4a6e7f4289d288854944eed6  # PR#170 (2026-08-21)
    with:
      base_branch: master
      version_manager: version-file
    secrets:
      REPO_ONLY_GITHUB_TOKEN: ${{ secrets.REPO_ONLY_GITHUB_TOKEN }}
