name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Test
        run: go test ./...